contact_links:
  - name: Community Support and Help
    url: https://starcitizen-lug.github.io
    about: Please ask for installation help in our Discord tech support channel. It's bridged to our Matrix space too!
